CLIENT_SECRET: /Users/davidfranz/.config/google/credentials.json
SCOPES: 
  - https://www.googleapis.com/auth/admin.directory.user
  - https://www.googleapis.com/auth/admin.datatransfer
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/spreadsheets